name: C language workflow

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    container: baoproject/bao:latest
    strategy:
      matrix:
        platform: ["qemu-aarch64-virt", "qemu-riscv64-virt"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: make PLATFORM=${{ matrix.platform }}

  coding-style:
    runs-on: ubuntu-latest
    container: baoproject/bao:latest
    strategy:
      matrix:
        platform: ["qemu-aarch64-virt", "qemu-riscv64-virt"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: make PLATFORM=${{ matrix.platform }} format-check

  static-analysis:
    runs-on: ubuntu-latest
    container: baoproject/bao:latest
    strategy:
      matrix:
        platform: ["qemu-aarch64-virt", "qemu-riscv64-virt"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: make PLATFORM=${{ matrix.platform }} tidy
      - run: make PLATFORM=${{ matrix.platform }} cppcheck

  misra:
    runs-on: ubuntu-latest
    container: baoproject/bao:latest
    strategy:
      matrix:
        platform: ["qemu-aarch64-virt", "qemu-riscv64-virt"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: make PLATFORM=${{ matrix.platform }} misra-check

  rops:
    runs-on: ubuntu-latest
    container: baoproject/bao:latest
    strategy:
      matrix:
        platform: ["qemu-aarch64-virt"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - run: git config --global --add safe.directory /__w/bao-partitioner/bao-partitioner
      - run: make PLATFORM=${{ matrix.platform }} rops-check

  his:
    runs-on: ubuntu-latest
    container: baoproject/bao:latest
    strategy:
      matrix:
        platform: ["qemu-aarch64-virt", "qemu-riscv64-virt"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: make PLATFORM=${{ matrix.platform }} his-check
