name: Build and Publish Bao Docker Container Image

on:
  push:
    branches: [ main ]
    paths: docker/Dockerfile

jobs:

  docker-build-publish-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: baoproj/bao:latest
